import { ArrowLeft, Mail, Lock, UserRound, Building2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import Logo from '../components/Logo'

export function AuthShell({ children, title, subtitle }) { return <div className="flex min-h-screen bg-sand"><div className="hidden w-2/5 flex-col justify-between bg-ink p-10 text-white lg:flex"><Logo light /><div><p className="eyebrow text-emerald-300">E-waste, reimagined</p><h1 className="mt-5 text-4xl font-bold leading-tight">A cleaner future starts with one responsible choice.</h1><p className="mt-5 max-w-sm leading-7 text-emerald-100/70">Join a transparent network that keeps valuable materials in use and out of landfills.</p></div><p className="text-sm text-emerald-100/50">Secure platform · Built for communities</p></div><div className="flex flex-1 flex-col px-5 py-8 sm:px-10"><div className="mx-auto w-full max-w-md"><Link to="/" className="mb-16 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-forest"><ArrowLeft size={16}/>Back to home</Link><div className="mb-8 lg:hidden"><Logo /></div><h2 className="text-3xl font-bold tracking-tight">{title}</h2><p className="mt-2 text-slate-500">{subtitle}</p>{children}</div></div></div> }
function Field({ label, icon: Icon, type = 'text', placeholder }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><div className="relative"><Icon className="absolute left-3 top-3 text-slate-400" size={18}/><input required type={type} placeholder={placeholder} className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none transition focus:border-forest focus:ring-2 focus:ring-forest/10"/></div></label> }
export function LoginPage() { const [email, setEmail] = useState(''); const navigate = useNavigate(); return <AuthShell title="Welcome back" subtitle="Sign in to manage your e-waste journey."><form className="mt-8 space-y-5" onSubmit={(e)=>{e.preventDefault(); navigate('/dashboard/household')}}><Field label="Email address" icon={Mail} type="email" placeholder="you@example.com"/><Field label="Password" icon={Lock} type="password" placeholder="Enter your password"/><div className="flex justify-end"><button type="button" className="text-sm font-semibold text-forest">Forgot password?</button></div><button className="btn-primary w-full">Sign in</button><p className="rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">Firebase Authentication is not configured yet. This form is UI-only and does not create a session.</p></form><p className="mt-8 text-center text-sm text-slate-500">New to E-Waste Connect? <Link to="/register" className="font-semibold text-forest">Create an account</Link></p></AuthShell> }
export function RegisterPage() { const navigate = useNavigate(); return <AuthShell title="Create your account" subtitle="Choose your role and join the connected ecosystem."><form className="mt-8 space-y-5" onSubmit={(e)=>{e.preventDefault(); navigate('/dashboard/household')}}><Field label="Full name" icon={UserRound} placeholder="Your name"/><Field label="Work email" icon={Mail} type="email" placeholder="you@example.com"/><Field label="Create password" icon={Lock} type="password" placeholder="At least 8 characters"/><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">I am joining as</span><div className="relative"><Building2 className="absolute left-3 top-3 text-slate-400" size={18}/><select className="w-full appearance-none rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-forest"><option>Household / Business</option><option>Collector</option><option>Authorized Recycler</option></select></div></label><button className="btn-primary w-full">Create account</button><p className="rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">Firebase Authentication is not configured yet. Registration is currently a frontend placeholder.</p></form><p className="mt-8 text-center text-sm text-slate-500">Already have an account? <Link to="/login" className="font-semibold text-forest">Sign in</Link></p></AuthShell> }
