import { ArrowUpRight, CalendarDays, CircleDollarSign, Leaf, Package, Recycle, Truck, Users } from 'lucide-react'
import DashboardLayout, { roles } from '../components/DashboardLayout'
import StatCard from '../components/StatCard'
import { EmptyState } from '../components/States'

const data = {
 household: { title: 'Good morning, there', intro: 'Keep your e-waste moving in the right direction.', stats: [['Items listed','0','Ready for collection',Package],['Collections','0','No upcoming collections',CalendarDays],['Estimated value','₹0','Indicative value',CircleDollarSign]], action: 'List e-waste' },
 collector: { title: 'Collector workspace', intro: 'Manage your pickups and keep every handover accountable.', stats: [['Active pickups','0','No assigned pickups',Truck],['This month','0 kg','Collected so far',Package],['Earnings','₹0','Pending settlements',CircleDollarSign]], action: 'View opportunities' },
 recycler: { title: 'Recycler workspace', intro: 'Receive verified material streams and report outcomes.', stats: [['Inbound requests','0','Awaiting acceptance',Recycle],['Processed','0 kg','This month',Package],['Diversion rate','—','Add your first record',Leaf]], action: 'Register intake' },
 admin: { title: 'Platform overview', intro: 'Monitor the health and transparency of the network.', stats: [['Total users','0','Awaiting Firebase setup',Users],['In circulation','0 kg','No records yet',Recycle],['Open cases','0','All clear',CircleDollarSign]] , action: 'Review activity' }
}
export default function DashboardPage() { const role = window.location.pathname.split('/')[2] || 'household'; const view = data[role] || data.household; return <DashboardLayout role={role}><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">{roles[role]}</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{view.title}</h1><p className="mt-2 text-slate-500">{view.intro}</p></div><button className="btn-primary"><ArrowUpRight size={17}/>{view.action}</button></div><div className="mt-8 grid gap-4 md:grid-cols-3">{view.stats.map(([label,value,detail,Icon])=><StatCard key={label} label={label} value={value} detail={detail} icon={Icon}/>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="card"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">Recent activity</h2><p className="mt-1 text-xs text-slate-500">Your latest platform updates</p></div><button className="text-sm font-semibold text-forest">View all</button></div><EmptyState title="No activity yet" text="Your collections, handovers and updates will show up here." /></section><section className="card p-5"><h2 className="font-bold">Indicative pricing</h2><p className="mt-1 text-xs leading-5 text-slate-500">Reference ranges updated by the network. Final value depends on quality and weight.</p><div className="mt-5 space-y-4">{[['Copper wire','₹420–₹560 / kg'],['Mixed electronics','₹35–₹80 / kg'],['Mobile phones','₹120–₹300 / unit']].map(([name,price])=><div className="flex justify-between border-b border-slate-100 pb-3 text-sm last:border-0" key={name}><span className="text-slate-600">{name}</span><span className="font-semibold text-forest">{price}</span></div>)}</div></section></div></DashboardLayout> }
