import { ArrowRight, BadgeCheck, BarChart3, CalendarCheck, CircleCheck, Leaf, MapPin, ShieldCheck, Smartphone } from 'lucide-react'
import { Link } from 'react-router-dom'
import PublicNav from '../components/PublicNav'

export default function LandingPage() {
  return <><PublicNav /><main>
    <section className="bg-white"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div><span className="eyebrow">Responsible disposal, connected</span><h1 className="mt-5 max-w-2xl text-4xl font-bold leading-tight tracking-tight text-ink sm:text-5xl lg:text-6xl">Make every device’s next step <span className="text-forest">count.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">E-Waste Connect brings communities, collectors and authorized recyclers together for a more transparent circular economy.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="btn-primary">Start your journey <ArrowRight size={17} /></Link><a href="#how-it-works" className="btn-secondary">See how it works</a></div><div className="mt-9 flex items-center gap-6 text-sm text-slate-500"><span className="flex items-center gap-2"><BadgeCheck size={17} className="text-forest" />Verified network</span><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-forest" />Traceable records</span></div></div><div className="relative rounded-2xl bg-mint p-7 sm:p-10"><div className="absolute right-6 top-6 rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-forest shadow-sm">Built for impact</div><div className="mx-auto flex max-w-sm flex-col gap-3 pt-6"><div className="card p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="rounded-lg bg-amber-50 p-2 text-amber-600"><Smartphone size={20} /></span><div><p className="text-sm font-semibold">Old smartphones</p><p className="text-xs text-slate-500">2.4 kg · Electronics</p></div></div><span className="text-sm font-bold text-forest">₹480</span></div></div><div className="ml-8 flex items-center gap-2 py-2 text-xs font-semibold text-forest"><div className="h-8 border-l-2 border-dashed border-forest/40" />Collection verified</div><div className="card p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-mint p-2 text-forest"><Leaf size={20} /></span><div><p className="text-sm font-semibold">Responsible recycling</p><p className="text-xs text-slate-500">Authorized partner · Certificate pending</p></div><CircleCheck className="ml-auto text-forest" size={19} /></div></div></div></div></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="max-w-xl"><span className="eyebrow">One connected ecosystem</span><h2 className="mt-3 text-3xl font-bold tracking-tight">From doorstep to responsible recycling.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[['01','List your e-waste','Tell us what you have and choose a convenient collection window.',CalendarCheck],['02','Get connected','A verified local collector picks up your items with a digital record.',MapPin],['03','Track the impact','Follow the journey to an authorized recycler and see your impact.',BarChart3]].map(([n,t,d,I])=><div className="card p-6" key={n}><span className="text-sm font-bold text-forest">{n}</span><I className="mt-7 text-forest" size={25}/><h3 className="mt-5 text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></section>
    <section id="impact" className="bg-ink py-16 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:grid-cols-3 lg:px-8"><div><p className="text-3xl font-bold">2.4M+</p><p className="mt-2 text-sm text-emerald-100/70">devices responsibly routed</p></div><div><p className="text-3xl font-bold">18k</p><p className="mt-2 text-sm text-emerald-100/70">collection partners</p></div><div><p className="text-3xl font-bold">100%</p><p className="mt-2 text-sm text-emerald-100/70">traceable handovers</p></div></div></section>
  </main><footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><LogoText /><span>© 2026 E-Waste Connect</span></div></footer></>
}
function LogoText() { return <span className="font-bold text-ink">E-Waste <span className="text-forest">Connect</span></span> }
